---
title: "Extract Trajectories around Aerodromes"
author: "Enrico Spinielli"
date: "12/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sf)
library(dplyr)
library(ggplot2)

```

## Test Case:

Data prepapration:
```{r}
t1 <- tribble(
  ~lon, ~lat, ~alt,
     0,    0,    0,
     1,    0,    1,
     2,    0,    2,
     3,    0,    3,
     4,    0,    4,
     5,    0,    5,
     6,    0,    6
)

t2 <- tribble(
  ~lon, ~lat, ~alt,
     0,    0,    0,
     1,    0,    1,
     2,    0,    2,
     3,    0,    3,
     3,    1,    4,
     3,    2,    5,
     4,    3,    6,
     5,    4,    6,
     5,    5,    6,
     4,    5,    6,
     3,    5,    6,
     2,    5,    6,
     1,    5,    6,
     0,    4,    6,
    -1,    3,    6,
    -2,    3,    6,
    -3,    3,    7,
    -4,    3,    8,
    -5,    3,    8,
    -6,    3,    8
)


trj1 <- t1 %>%
  st_as_sf(coords = c("lon", "lat", "alt"), crs = 4326, dim = "XYZ") %>%
  summarise(geometry = st_combine(geometry)) %>%
  st_cast("LINESTRING")

trj2 <- t2 %>%
  st_as_sf(coords = c("lon", "lat", "alt"), crs = 4326, dim = "XYZ") %>%
  summarise(geometry = st_combine(geometry)) %>%
  st_cast("LINESTRING")


apt <- st_point( x = c(0, 0, 0), dim = "XYZ") %>%
  st_sfc(crs = 4326) %>%
  st_buffer(dist = 4.5)
```

A circle around an aerodrome and a simple trajectory:
```{r simple-intersection}
ggplot() + geom_sf(data = trj1) + geom_sf(data = apt, fill = NA) + geom_sf(data = trj1 %>% st_cast("POINT"))
```

A circle around an aerodrome and a subtle trajectory:
```{r subtle-intersection}
ggplot() + geom_sf(data = trj2) + geom_sf(data = apt, fill = NA) + geom_sf(data = trj2 %>% st_cast("POINT"))

```

With `sf` we obtain two portions
```{r sf-intersections}
trj2 %>%
  st_zm() %>%
  st_intersection(apt) %>% 
  st_cast("LINESTRING")
```

